### ISSUE TITLE
How to upgrade cefglue?

### ISSUE THREAD

**Issue by kice** [aleab/cef-unity-sample#2]
I complied a newer version of CefGlue (with a custom build of cef); but if I run the game it will crash.

I would like to know how to compile CefGlue for unity. I cannot find any doc about this topic.

The examples (including the WPF OSR example) come with CefGlue work fine on Win10 64bit.

**Comment by aleab** [comment]
I have a few questions.
Did you get any error message or log file?
How are you running the game? Are you using a compiled executable or are you just running it through the Unity Editor?

As far as I remember, building CefGlue is pretty straightforward. As I've written in the readme of this repository, be sure to target a compatible .NET Framework; if you are using one of the latest versions of Unity, I think you might be able to target up to .NET 4.6, otherwise stick with .NET 3.5.

**Comment by kice** [comment]
Did you get any error message or log file?
```
CefUnitySample [version: Unity 2017.2.0f3 (46dda1414e51)]

mono.dll caused an Access Violation (0xc0000005)
  in module mono.dll at 0033:10e93e55.
```

How are you running the game? Are you using a compiled executable or are you just running it through the Unity Editor?
Both Unity Editor and compiled exe will crash.

The Unity will not import the CefGlue unless I use .NET 3.5. 
And I have tried a lot other methods but none of them would work.

They both will crash before I see the scene.

---

I modified the dll of CefGlue in your code, changing the `CefGlue/Interop/version.g.cs` to load my libcef.dll. Using this way, I can see the scene but then also crashes but for another reason. 
```
NullReferenceException: Object reference not set to an instance of an object
at Xilium.CefGlue.CefRenderHandler.get_screen_point (Xilium.CefGlue.Interop.cef_render_handler_t*,Xilium.CefGlue.Interop.cef_browser_t*,int,int,int*,int*) <IL 0x00022, 0x00098>

========== OUTPUTING STACK TRACE ==================

0x00007FF8F716A7D9 (libcef) GetHandleVerifier
0x00007FF8F71120D6 (libcef) GetHandleVerifier
0x00007FF8F7112162 (libcef) GetHandleVerifier
0x00007FF96574B85D (USER32) CallWindowProcW
0x00007FF96574B1EF (USER32) DispatchMessageW
0x00007FF8FD5578E4 (UnityPlayer) TranslateAndDispatchFilteredMessage
0x00007FF8FD4F0D08 (UnityPlayer) TitleBarTimerUpdateCallback
0x00007FF8FD4FE2DD (UnityPlayer) UnityMain
0x00007FF6125013EE (cef-unity-sample) __scrt_common_main_seh
0x00007FF966851FE4 (KERNEL32) BaseThreadInitThunk
0x00007FF966BEEF91 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========
```

I am new to unity and C#, and I have tried my best to solve it.

**Comment by aleab** [comment]
> I modified the dll of CefGlue in your code, changing the `CefGlue/Interop/version.g.cs` to load my libcef.dll.

Unfortunately it's not that simple.

The entire CefGlue codebase is highly dependent on the version of the native library they put in that autogenerated file. If your version of *libcef.dll* is different from the one declared in that file, you'll have to modify the whole CefGlue source to make it work with your version; you can't just change the version number declared in the `version.g.cs` file.

Did you modify the *libcef.dll* library yourself or did download it from somewhere? Can you attach it here so that I can test it myself?
Also, if you modified it yourself, what version of *libcef* did you use? And what changes did you make?

---

Did you get the first crash with the version of CefGlue included with this project or with the one you compiled? Were you already using your custom version of *libcef.dll* when you got the first crash?

Last question: did you modify the code of this project?
<br/>
I'm sorry for all these questions, but I need information to be able to reproduce your issue and get you on the right track to solve it. 😄
